### ISSUE TITLE
Getting started with LSP

### ISSUE THREAD

**Issue by manuEbg** [MopeSWTP-SS21/MopeSWTP#29]
Find Answers to the following Questions:

- [x] What is LSP and how does it Work?
- [x] How can we Integrate it into the Mo|E-Server?
- [x] How can we easily send and Request LSP-Messages? (maybe some Kind of Console-Client)

Due by next (Daily)-Scrum-Meeting (Wed. )

**Comment by CSchoel** [comment]
Since @manuEbg told me that you had trouble finding good examples to start with the LSP implementation, I took the liberty to do a quick search myself. Maybe you already know of all these projects, but the most promising links I found were the following:

* https://github.com/Microsoft/vscode-extension-samples/tree/main/lsp-sample - well-documented official sample implementation in Typescript.
* https://code.visualstudio.com/api/language-extensions/language-server-extension-guide - official VS code documentation discussing the above example
* https://github.com/eclipse/eclipse.jdt.ls - LSP server for Java using LSP4J
* https://github.com/georgewfraser/java-language-server - LSP server using a [custom minimalist LSP implementation](https://github.com/georgewfraser/java-language-server/blob/43ffea436b9b726eb8d6721605e9c437333105b9/src/main/java/org/javacs/lsp/README.md)
* https://github.com/dragos/dragos-vscode-scala - LSP server for Scala using custom LSP impementation based on [ensime](https://ensime.github.io/)
  * seems to be outdated (see next entry)
* https://github.com/scalameta/metals - LSP server for Scala using LSP4J
* https://www.eclipse.org/community/eclipse_newsletter/2017/may/article2.php - minimal example using LSP4J from the eclipse newsletter
* https://www.vogella.com/tutorials/EclipseLanguageServer/article.html - LSP4J tutorial by Lars Vogel (whose tutorials I have previously [roasted on my blog](https://arbitrary-but-fixed.net/teaching/java/2018/12/09/mergesort.de.html), but they should be OK for your purposes :laughing: )

**Comment by CSchoel** [comment]
I'll also drop a link to my new repo here for reference: https://github.com/MopeSWTP-SS21/LSP4J-test-CS
