### ISSUE TITLE
Getting started with ZeroMQ

### ISSUE THREAD

**Issue by manuEbg** [MopeSWTP-SS21/MopeSWTP#30]
Find Answers to the following Questions:

- [x] What is ZeroMQ and how does it Work?
- [x] How can we Integrate it into the Mo|E-Server?
- [x] What is the Connection between CORBA and ZeroMQ?
- [ ] What is the Purpose of https://github.com/THM-MoTE/omc-java-api?

Due by next (Daily)-Scrum-Meeting (Wed. )

**Comment by CSchoel** [comment]
FYI: The current Mo|E version already communicates with the OMC via ZMQ. The CORBA interface is deprecated and should be discontinued in your new version in order to support Java >= 9.

Also watch out for concurrency issues with ZMQ:

* https://github.com/THM-MoTE/ModelicaScriptingTools.jl/issues/9
* https://github.com/OpenModelica/OMJulia.jl/issues/12
* https://github.com/OpenModelica/OMJulia.jl/issues/32
* https://github.com/OpenModelica/OMJulia.jl/issues/39

This is probably due to poor configuration in OMJulia, but some error sources may also reside in the OMC implementation itself and thus affect Mo|E.
