### ISSUE TITLE
ServerConfig

### ISSUE THREAD

**Issue by manuEbg** [MopeSWTP-SS21/MopeSWTP#35]
We need a Server Config Class/File
should contain:

- Path to omc Executable
- port
- locale ?

**Comment by IlmarB** [comment]
So I have started an attempt - referencing to the mope.cfg file of the mope-server I can easily create the needed server.cfg. But .. 
What I do not understand is the constructor of OMCAdapter-Class. So @CSchoel, what exactly is the purpose of the parameters in class MopeLSPServer

`workspaceService.InitOMC( new OMCAdapter("/usr/bin/omc", "us", "mope_local" ));`

and the definition in OMCAdapter 

` public OMCAdapter(String omcExecPath, String locale, String fileProviderSuffix){
        omc = new ZeroMQClient(omcExecPath, locale, new ZMQPortFileProvider(fileProviderSuffix));
        logger.info("OMCAdapter initialized");
    }`

**Comment by IlmarB** [comment]
I mean the first one is kinda self-explanatory, that is the path to the omc. But what about the other two?

**Comment by CSchoel** [comment]
I know as much about these classes as you, but by traversing a little through the code ("go to definition" is your friend :wink:) I found out the following:

* The `locale` is not uses for a [`java.util.Locale`](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/Locale.html) as I first suspected, but instead it sets the [`LANG`](https://www.ibm.com/docs/en/sva/7.0.0?topic=SSPREK_7.0.0/com.ibm.isam.doc_70/gsk_capicmd_user19.htm) environment variable [for the OMC process](https://github.com/THM-MoTE/omc-java-api/blob/48c27b7d7c3eea3914be2a3c46f4c33112a8e5f6/src/main/java/omc/OmcExecuter.java#L48). I guess this influences the language in which OMC reports errors.
* The `ZMQPortFileProvider` is a helper class that is [used to find the ZMQ port file](https://github.com/THM-MoTE/omc-java-api/blob/48c27b7d7c3eea3914be2a3c46f4c33112a8e5f6/src/main/java/omc/ior/ZMQPortFileProvider.java#L26). As far as I understand, this port file is an actual file on the file system, which is used by ZMQ to communicate between processes. The OMC creates this file when it is started and the omc-java-api has to find it in order to establish a ZMQ connection to the OMC process. The default suffix is `om_local`. I am not sure if this suffix can change depending on the OS or OMC arguments. You have to figure that out by trial and error unless @njustus has documented this somewhere or you can find the information in the OpenModelica documentation.
* I would suspect that most of the time you will not need those arguments at all. You can simply create a client with `new ZeroMQClient(omExecPath)` and it will use the `LANG` variable of the OS and the default suffix `om_local`.

**Comment by manuEbg** [comment]
@IlmarB  maybe this is a little help:)
https://github.com/MopeSWTP-SS21/LspConsole/commit/dd7a1c3161435c787ab49adc3e30df47f7c1176b

I got inspired by https://stackoverflow.com/questions/16273174/how-to-read-a-configuration-file-in-java

**Comment by njustus** [comment]
>  I guess this influences the language in which OMC reports errors.

Yes it does! If you do not provide the LANG variable on localized systems `omc` produces half-localized error messages. They are mostly unreadable.

If you don't need to support multiple projects at once, you _don't need_ the parameter `suffixProvider`. In this scenario you need unique port files **per project** which is highly application specific. If the suffix isn't provided omc will always *reuse* the running instance, which in turn causes race condition nightmares!

> I would suspect that most of the time you will not need those arguments at all. You can simply create a client with new ZeroMQClient(omExecPath) and it will use the LANG variable of the OS and the default suffix om_local.

Yes!

BTW: I would highly recommend using [HOCON](https://github.com/lightbend/config) or YAML for your configuration files. Unless you are using Spring Boot for parsing property files into `@Configuration` classes its extremely difficult to use them consistently throughout your application.

Sidenote: Skimming through the mope and webmodelica thesis could improve your understanding of Modelica and OMC.

**Comment by CSchoel** [comment]
@IlmarB This issue has not received any updates in the last week. What is your status?

**Comment by CSchoel** [comment]
Currently, the server config is loaded from `src/main/java/Server/server.config`. This is bad practice, because:

* It assumes that everybody who wants to run the server has the source files lying around next to the server executable.
* It conflates data and code directories.
* It does not follow common operating system conventions for storing configuration data of applications (e.g. most Linux systems use a file like `~/.mope` or `~/.config/mope/mope.conf`, while windows uses something like `%APPDATA%\mope\mope.conf`). Note: If you should choose the `~/.config/mope/mope.conf` route on linux, please make sure that either a) your config is compatible with the old Mo|E version by nico, or b) you choose a slightly different name than `mope` for the directory.

**Comment by IlmarB** [comment]
nothing done for that yet

**Comment by CSchoel** [comment]
@IlmarB It has been another week without update. Can you please keep us posted about the status of this issue?

**Comment by IlmarB** [comment]
I actually forgot about this one 🙈 will do until friday

**Comment by IlmarB** [comment]
done - see branch `feature/cfgAndShutDown`
