### ISSUE TITLE
Documentation for JSON RPC Call checkModel(String modelName)

### ISSUE THREAD

**Issue by IlmarB** [MopeSWTP-SS21/MopeSWTP#63]
Create the documentation for the checkModel Request. It will be documented in our [Wiki](https://github.com/MopeSWTP-SS21/MopeSWTP/wiki/JSON-RPC-Calls-Documentation#checkmodel-request)

**Comment by IlmarB** [comment]
I have described in general what the rpc calls do. The more specific decription will follow up tomorrow.

**Comment by IlmarB** [comment]
Since this issue was originally intended to describe just the `checkModel` call I am going to close it. I have finished the original task. The more detailled description will be discussed in a separate issue.

**Comment by CSchoel** [comment]
Can you be more specific what you want to add to the description? I would like to see an explanation which OpenModelica Scripting commands are used by the JSON RPC and a more detailed definition of the parameters (e.g. specify that `modelName` must be a fully qualified name of a Modelica model that can be found in the Modelica path).

Also I believe that you do not have to specify that the client has to call `get()`, since this is not specific to the JSON RPC call but a general concept involving futures/promises. I am also not sure what the sentence "In case the method has not been used null is returned." means. In general, as a user, I want to know:

* how to structure my input so that it is accepted by the call
* how the output is structured, i.e. how can I extract the information that is relevant for my specific use case
* what are the changes to the internal state of the server and/or OMC instance introduced by the call.

Also as a last remark, I believe that this issue (judging from the title) might already be a little too fine grained. Just add a checklist to #52 .  Otherwise, the overhead of writing issues is larger than the time required to actually write the documentation.

**Comment by IlmarB** [comment]
okay thanks for the hints
